### ISSUE TITLE
How do I load .env when starting Mix Phoenix.server

### ISSUE THREAD

**Issue by ACPK** [avdi/dotenv_elixir#20]
Sorry for the question, but how do I load the .env file when running Mix Phoenix.server?

Here is my mix.exs:

    defmodule PhoenixTokenAuthReact.Mixfile do
      use Mix.Project

      def project do
        [app: :phoenix_token_auth_react,
         version: "0.0.1",
         elixir: "~> 1.0",
         elixirc_paths: ["lib", "web"],
         compilers: [:phoenix] ++ Mix.compilers,
         deps: deps]
      end

      # Configuration for the OTP application
      #
      # Type `mix help compile.app` for more information
      def application do
        [mod: {PhoenixTokenAuthReact, []},
         applications: app_list(Mix.env) ]
      end

      defp app_list(:test), do: [:hound | app_list]
      defp app_list(:dev), do: [:dotenv | app_list]
      defp app_list(_),     do: app_list
      defp app_list, do: [:phoenix, :cowboy, :logger]

      # Specifies your project dependencies
      #
      # Type `mix help deps` for examples and options
      defp deps do
        [{:phoenix, "~> 0.12.0"},
         {:phoenix_ecto, "~> 0.3.2"},
         {:phoenix_live_reload, "~> 0.3.3"},
         {:postgrex, ">= 0.0.0"},
         {:phoenix_token_auth, "0.0.13"},
         # use github mailgun repo for phoenix token auth to have testing mode
         {:cowboy, "~> 1.0"},
         {:dotenv, "~> 1.0.0"},
         {:hound, ">= 0.6.0", only: :test},
         {:timex, "~> 0.13.4"},
        ]
      end
    end

**Comment by jarednorman** [comment]
I take it you figured it out your issue?

**Comment by ACPK** [comment]
@jarednorman I never got it to work.  Any suggestions?

**Comment by jarednorman** [comment]
That looks to be configured correctly. Can you link me to the project so I can take a look?

**Comment by jarednorman** [comment]
No response. Closing.
