### ISSUE TITLE
Problem: Access protocol is deprecated

### ISSUE THREAD

**Issue by c-rack** [avdi/dotenv_elixir#22]
Compiling a project using dotenv with Elixir 1.1.0-dev gives the following deprecation warning:

```
lib/dotenv/env.ex:23: warning:
implementation of the Access protocol is deprecated.
For customization of the dict[key] syntax, please implement the Dict behaviour instead
```

**Comment by mitchellhenke** [comment]
I'd be willing to take a shot at fixing this, but am unsure which direction to go. To keep the `dict[key]` syntax available, DotEnv.Env would have to implement the entire Dict API, which seems off to me.

Jose recommends [here](https://github.com/elixir-lang/elixir/issues/2973#issuecomment-84333469) using helper functions to access it, as DotEnv.Env is not a Dict, but has one underneath. If that is the way to go, I'd be glad to tackle it.
