### ISSUE TITLE
Version release for elixir 1.4.x warning fixes

### ISSUE THREAD

**Issue by imsoulfly** [avdi/dotenv_elixir#31]
Hi,

I have a question regarding the fixes of the warnings that are currently in master branch. 
Would love to see a versions release for these so that we can rid of some warnings in our project.

Do you have any date in mind when this could be possible?

Cheers,
Ingo

**Comment by jarednorman** [comment]
Just setting up a new laptop, I'll try to get this out this week.

**Comment by jarednorman** [comment]
Released 3.0.0! 🤘 🎉

**Comment by imsoulfly** [comment]
Thank you very much for your efforts!
