### ISSUE TITLE
configure the .env file to load before application starts

### ISSUE THREAD

**Issue by axelson** [avdi/dotenv_elixir#32]
Is it possible to configure what `.env` file to load before any are loaded?

My current use-case is that I want to load `.env` in development, and `.env.test` in test (but ensure `.env` is not loaded in the test environment), but I'm unable to find a way to do that at the moment.

**Comment by jarednorman** [comment]
You can. See the "Serverless API" section of the README.

**Comment by axelson** [comment]
But wouldn't that load those environment variables in addition to the `.env` variables? Am I missing something? It seems like the environment variables are just loaded automatically as soon as the application starts. I also feel like I don't understand the meaning of "Serverless" in this context.

**Comment by jarednorman** [comment]
I believe the answer is no, so long as you haven't added Dotenv to your app_list.

**Comment by axelson** [comment]
@jarednorman thanks! Removing `:dotenv` from the app_list is the step that I was missing.

**Comment by jarednorman** [comment]
Awesome, glad it worked out. 😄

**Comment by axelson** [comment]
For reference on Elixir 1.6+ (which autostarts deps) you now need a deps entry with `runtime: false`:
```
  defp deps do
    [
      {:dotenv, "~> 3.0", only: [:dev, :test], runtime: false}
    ]
  end
```
